import { addDays, subDays } from 'date-fns';

export const MOCK_ACCOUNTS = [
  {
    id: '1',
    username: 'telegram_user1',
    nickname: 'Marketing Bot 1',
    healthScore: 95,
    proxy: 'proxy1.example.com',
    phoneNumber: '+1234567890',
    accountAge: subDays(new Date(), 120),
    lastActive: new Date(),
    status: 'active',
  },
  {
    id: '2',
    username: 'power_user2',
    nickname: 'Sales Bot',
    healthScore: 88,
    proxy: 'proxy2.example.com',
    accountAge: subDays(new Date(), 90),
    lastActive: subDays(new Date(), 1),
    status: 'active',
  },
  {
    id: '3',
    username: 'tg_marketer3',
    healthScore: 75,
    proxy: 'proxy3.example.com',
    phoneNumber: '+1987654321',
    accountAge: subDays(new Date(), 60),
    lastActive: subDays(new Date(), 2),
    status: 'limited',
  },
  {
    id: '4',
    username: 'business_acc4',
    nickname: 'Support Bot',
    healthScore: 92,
    accountAge: subDays(new Date(), 180),
    lastActive: new Date(),
    status: 'active',
  },
  {
    id: '5',
    username: 'social_pro5',
    healthScore: 85,
    proxy: 'proxy5.example.com',
    accountAge: subDays(new Date(), 150),
    lastActive: subDays(new Date(), 1),
    status: 'active',
  },
  {
    id: '6',
    username: 'tg_expert6',
    nickname: 'Customer Service 1',
    healthScore: 78,
    proxy: 'proxy6.example.com',
    phoneNumber: '+1122334455',
    accountAge: subDays(new Date(), 45),
    lastActive: subDays(new Date(), 3),
    status: 'active',
  },
  {
    id: '7',
    username: 'messaging_pro7',
    healthScore: 65,
    accountAge: subDays(new Date(), 30),
    lastActive: subDays(new Date(), 5),
    status: 'limited',
  },
  {
    id: '8',
    username: 'tg_master8',
    nickname: 'Announcements Bot',
    healthScore: 98,
    proxy: 'proxy8.example.com',
    phoneNumber: '+9988776655',
    accountAge: subDays(new Date(), 240),
    lastActive: new Date(),
    status: 'active',
  },
  {
    id: '9',
    username: 'comm_expert9',
    healthScore: 82,
    proxy: 'proxy9.example.com',
    accountAge: subDays(new Date(), 100),
    lastActive: subDays(new Date(), 2),
    status: 'active',
  },
  {
    id: '10',
    username: 'tg_leader10',
    nickname: 'Community Bot',
    healthScore: 90,
    proxy: 'proxy10.example.com',
    phoneNumber: '+5544332211',
    accountAge: subDays(new Date(), 200),
    lastActive: subDays(new Date(), 1),
    status: 'active',
  },
] as const;

export const NAVIGATION_ITEMS = [
  { name: 'Dashboard', href: '/', icon: 'BarChart3' },
  { name: 'Accounts', href: '/accounts', icon: 'Users' },
  { name: 'Messages', href: '/messages', icon: 'MessageSquare' },
  { name: 'Warmup', href: '/warmup', icon: 'Zap' },
  { name: 'Settings', href: '/settings', icon: 'Settings' },
] as const;